//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADON
    {
        public long MAHOADON { get; set; }
        public long MAHANG { get; set; }
        public int SOLUONG { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual HANG HANG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
