//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG
    {
        public HANG()
        {
            this.CTHOADON = new HashSet<CTHOADON>();
        }
    
        public long MAHANG { get; set; }
        public string TENHANG { get; set; }
        public int SOLUONG { get; set; }
        public double GIA { get; set; }
        public Nullable<long> MANCC { get; set; }
        public Nullable<long> MALOAI { get; set; }
        public Nullable<long> MAKHO { get; set; }
    
        public virtual ICollection<CTHOADON> CTHOADON { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
