//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public long MAKM { get; set; }
        public string TENKM { get; set; }
        public double PHANTRAM { get; set; }
        public double GIAMTOIDA { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public Nullable<long> MATAIKHOAN { get; set; }
    }
}
