


CREATE TABLE NHACUNGCAP(
	MANCC BIGINT IDENTITY(1, 1) PRIMARY KEY, 
	TENNCC NVARCHAR(255) NOT NULL, 
	MOTA NVARCHAR(255)
)

CREATE TABLE LOAIHANG(
	MALOAI BIGINT IDENTITY(1, 1) PRIMARY KEY, 
	TENLOAI NVARCHAR(50) NOT NULL, 
	MOTA NVARCHAR(255),
)

CREATE TABLE KHO(
	MAKHO BIGINT IDENTITY(1, 1) PRIMARY KEY,
	TENKHO NVARCHAR(50) NOT NULL, 
	DIACHI NVARCHAR(255) NOT NULL,
	MOTA NVARCHAR(255)
)

CREATE TABLE HANG (
	MAHANG BIGINT IDENTITY(1, 1) PRIMARY KEY, 
	TENHANG NVARCHAR(255) NOT NULL, 
	SOLUONG INT NOT NULL, 
	GIA FLOAT NOT NULL,
	MANCC BIGINT,
	MALOAI BIGINT,
	MAKHO BIGINT,
	CONSTRAINT FK_HANG_MANCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC), 
	CONSTRAINT FK_HANG_MALOAI FOREIGN KEY(MALOAI) REFERENCES LOAIHANG(MALOAI), 
	CONSTRAINT FK_HANG_MAKHO FOREIGN KEY(MAKHO) REFERENCES KHO(MAKHO)
)

CREATE TABLE TAIKHOAN(
	MATAIKHOAN BIGINT IDENTITY(1, 1) PRIMARY KEY, 
	TEN NVARCHAR(100) NOT NULL, 
	DIACHI NVARCHAR(100), 
	GIOITINH BIT,
	SDT VARCHAR(12), 
	NGAYSINH DATETIME,
)

CREATE TABLE KHACHHANG(
	MAKH BIGINT IDENTITY(1, 1) PRIMARY KEY,
	MATAIKHOAN BIGINT, 
	CONSTRAINT FK_KHACHHANG_MATAIKHOAN FOREIGN KEY(MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN)
)

CREATE TABLE NHANVIEN(
	MANHANVIEN BIGINT IDENTITY(1, 1) PRIMARY KEY,
	MATAIKHOAN BIGINT, 
	CONSTRAINT FK_NHANVIEN_MATAIKHOAN FOREIGN KEY(MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN)
)

CREATE TABLE KHUYENMAI(
	MAKM BIGINT IDENTITY(1, 1) PRIMARY KEY,
	TENKM NVARCHAR(50) NOT NULL, 
	PHANTRAM FLOAT NOT NULL, 
	GIAMTOIDA FLOAT NOT NULL,
	NGAYKETTHUC DATETIME NOT NULL,
	MATAIKHOAN BIGINT
)

CREATE TABLE HOADON(
	MAHOADON BIGINT IDENTITY(1, 1) PRIMARY KEY,
	MANHANVIEN BIGINT, 
	MAKH BIGINT,
	TONGTIEN FLOAT,
	NGAYLAP DATETIME NOT NULL,
	TINHTRANG TINYINT NOT NULL, 
	CONSTRAINT FK_HOADON_MANHANVIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	CONSTRAINT FK_HOADON_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTHOADON(
	MAHOADON BIGINT,
	MAHANG BIGINT,
	SOLUONG INT NOT NULL,
	THANHTIEN FLOAT,
	CONSTRAINT PK_CTHOADON PRIMARY KEY(MAHOADON, MAHANG),
	CONSTRAINT FK_CTHOADON_MAHOADON FOREIGN KEY(MAHOADON) REFERENCES HOADON(MAHOADON),
	CONSTRAINT FK_CTHOADON_MAHANG FOREIGN KEY(MAHANG) REFERENCES HANG(MAHANG)
)